# Generated by Django 5.0.6 on 2024-06-27 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Central_Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(max_length=200, null=True, upload_to='Dari-Mooch-Central-Images/')),
            ],
        ),
    ]
