# Generated by Django 5.0.6 on 2024-07-02 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contact_Us', '0002_rename_first_name_contact_us_firstname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact_us',
            name='firstname',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
