# Generated by Django 5.0.6 on 2024-07-02 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contact_Us', '0003_alter_contact_us_firstname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact_us',
            name='email',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
