# Generated by Django 5.0.6 on 2024-07-02 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contact_Us', '0004_alter_contact_us_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact_us',
            name='message',
            field=models.TextField(null=True),
        ),
    ]
