# Generated by Django 5.0.6 on 2024-07-02 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contact_Us', '0005_alter_contact_us_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact_us',
            name='lastname',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
