# Generated by Django 5.0.6 on 2024-07-02 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contact_Us', '0006_alter_contact_us_lastname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact_us',
            name='phone',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
