# Generated by Django 5.0.6 on 2024-06-27 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dari_Mooch_Products', '0002_products_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='price_off',
            field=models.IntegerField(null=True),
        ),
    ]
