# Generated by Django 5.0.6 on 2024-06-27 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dari_Mooch_Products', '0003_products_price_off'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='price_off',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
